config/routes.rb
WishlistApp::Application.routes.draw do

  devise_for :users
  root to: 'wishlist#show'

  get "js/bookmarklet(.:format)" => "js#bookmarklet", :as => :bookmarklet
  get "/add_wishlistitem" => "wishlist#add_wishlistitem", as: :add_wishlistitem
  get "/:user_id" => "wishlist#show", as: :wishlist
  delete "/wishlist/:id" => "wishlist#delete_wishlistitem", as: :delete_wishlistitem

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :wishlist
  has_many :wishlistitems, through: :wishlist

  after_create :create_wishlist

  def create_wishlist
    Wishlist.create(user_id: self.id)
  end
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
#  attr_accessible :user_id

  belongs_to :user
  has_many :wishlistitems

end

app/models/wishlistitem.rb
class Wishlistitem < ActiveRecord::Base
#  attr_accessible :image, :price, :title, :url, :wishlist_id

  belongs_to :wishlist

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/js_controller.rb
class JsController < ApplicationController
  layout false

  def bookmarklet
  end
end

app/controllers/wishlist_controller.rb
class WishlistController < ApplicationController
	before_filter :authenticate_user!, except: :add_wishlistitem

  def show
    @user = current_user
    @wishlistitems_backwards = @user.wishlistitems
    @wishlistitems = @wishlistitems_backwards.reverse 
  end

  def add_wishlistitem
    unless current_user
        respond_to do |format|
          format.js { render partial: '/wishlist/fail.js.erb' }
        end
      else

        wishlist = current_user.wishlist.id
        title = params[:title]
        image = params[:image]
        price = params[:price]
        link_url = params[:link_url]

        @wishlistitem = Wishlistitem.create(wishlist_id: wishlist, title: title, image: image, price: price, url: link_url)
        
        if @wishlistitem.save          
          respond_to do |format|
            format.js
          end
        end
      end
end
    def delete_wishlistitem
       @wishlistitem = Wishlistitem.find(params[:id])
         @wishlistitem.destroy

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/js_helper.rb
module JsHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/js/bookmarklet.js.erb
(function (){

	initMyBookmarklet();
	
	function initMyBookmarklet() {
		(window.myBookmarklet = function() {
			
				function get_amazon_product_info() 
			 	{
			 		var title_span = document.getElementById("btAsinTitle");
			 		var title = title_span.innerText;
			 		var image_tag = document.getElementById("main-image");
			 		var image = image_tag.getAttribute("src");
			 		var price_span = document.getElementById("actualPriceValue");
			 		var price_with_dollar = price_span.innerText;
			 		var price = strip_dollar(price_with_dollar);
			 		var link_url = document.URL;
			 		var product_info = {
			 			title: title,
			 			image: image,
			 			price: price,
			 			link_url: link_url
			 		};
			 		if (product_info)
				 		{
				 			console.log(product_info);
				 			return product_info;
				 		}
				 	else
				 		{
				 			alert("Something went wrong!");
				 		}
		 		}

			 	function get_etsy_product_info()
			 	{
			 		var title_span = document.getElementById("listing-page-cart-inner").getElementsByTagName("span");
                                        var title = title_span[0].innerText;
                                        var image_div = document.getElementById("image-main");
                                        var image_tag = image_div.getElementsByTagName("img");
                                        var image = image_tag[0].getAttribute("src");
                                        var price_span = document.getElementById("listing-price").getElementsByClassName("currency-value");
                                        var price = price_span[0].innerText;
                                        var link_url = document.URL;
                                        var product_info = {
                                                title: title,
                                                image: image,
                                                price: price,
                                                link_url: link_url
                                        };
                                        if (product_info)
                                        {
                                                console.log(product_info);
                                                return product_info;
                                        }
                                        else
                                        {
                                                alert("Something went wrong!");
                                        }	

				}

			 	function get_jcrew_product_info()
			 	{
			 		var title_span = document.getElementById("productDetailsContainer0");
                                     	var title = title_span.getElementsByTagName("h1")[0].innerText;
                                        var image_div = document.getElementById("subContainer");
                                        var image_tag = image_div.getElementsByTagName("img");
                                        var image = image_tag[0].getAttribute("src");
                                        var price_div = document.getElementById("productDetailsContainer0");
                                        var price_span = price_div.getElementsByClassName("full-price");
                                        var price_with_dollar = price_span[0].innerText;
                                        var price_with_possible_space = strip_dollar(price_with_dollar);
                                        var price = strip_space(price_with_possible_space);
                                        var link_url = document.URL;
                                        var product_info = {
                                                title: title,
                                                image: image,
                                                price: price,
                                                link_url: link_url
                                        };
                                        if (product_info.title = title)
                                        {
                                                return product_info;
                                        }
                                        else
                                        {
                                                console.log("No product_info object");
                                                alert("Something went wrong!");
                                                }	
				}

			 	function determine_params() 
				{
				 		switch (document.domain) {
					 		case "www.amazon.com":
					 			var amazon = get_amazon_product_info();
					 			return amazon;
					 			break;
					 		case "www.etsy.com":
								var etsy = get_etsy_product_info();
								return etsy;
								break;
					 		case "www.jcrew.com":
					 			var jcrew = get_jcrew_product_info();
					 			return jcrew;
					 			break;
					 		default:
					 			alert("This is not a supported page!");
				 		}
				}	

				function send_data(product_info)
				{
					var domain = 'http://young-harbor-6978.herokuapp.com/add_wishlistitem?';
					var url = domain + "title=" + encodeURIComponent(product_info.title) + "&image=" + encodeURIComponent(product_info.image) + "&price=" + encodeURIComponent(product_info.price) + "&link_url=" + encodeURIComponent(product_info.link_url);
					
					var script = document.createElement('script'); 
					script.setAttribute('language','javascript'); 
					script.setAttribute('src', url); 
					document.body.appendChild(script);
				}

				function strip_dollar(string)
				{
					var stripped = "";
					for ( var i = 0; i < string.length; i++ )
					{
						if (string.charAt(i) != "$")
						{
							stripped += string.charAt(i);
						}
					};
					return stripped
				}

				function strip_space(string)
                                {
                                        var stripped = "";
                                        for ( var i = 0; i < string.length; i++ )
                                        {
                                                if (string.charAt(i) != " ")
                                                {
                                                        stripped += string.charAt(i);
                                                }
						else
						{
							return stripped
						}
                                        };
                                        return stripped
                                }  
				var product_info = determine_params();
				send_data(product_info);
		})();
	}

})();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WishlistApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav">
	  <% if user_signed_in? %>
	    &nbsp &nbsp Signed in as <%= current_user.email %>. Not you?
	    &nbsp &nbsp <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  <% else %>
	    &nbsp &nbsp <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	  <% end %>

          <% if current_user %>
                <h3> Use the Wish List App to bookmark information about products from Amazon, J Crew, and Etsy</h3>
		<span style="visibility: visible; text-decoration: underline"> <h4> ---------------------------> ONLY the Chrome web browser is fully supported for all three sites!!!!!!! Sorry. :( <--------------------------- </h4> </span>
                        <a class="bookmarklet btn" href="javascript:(function () { var s = document.createElement('script'); s.setAttribute('language','javascript'); s.setAttribute('src','http://young-harbor-6978.herokuapp.com/js/bookmarklet.js'); document.body.appendChild(s);})()">Bookmark Item (Chrome ONLY)</a>
                        <------------ Drag this bookmarklet into your <u> Chrome </u> web browser's toolbar
        <% end %>

<%= yield %>

</body>
<footer>
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
</br>
<p>Raymond Dias</p>
<p>General Assembly - Project</p>
<p>July 10th 2013</p>
</footer>
</html>

app/views/wishlist/_fail.js.erb
alert("Error! Error! You need to be logged into the Wish List App to use this bookmarklet!")

app/views/wishlist/add_wishlistitem.html.erb
<h1>Wishlist#add_wishlistitem</h1>
<p>Find me in app/views/wishlist/add_wishlistitem.html.erb</p>

app/views/wishlist/add_wishlistitem.js.erb
alert("This item is now Saved in your Wish List App!!!");

app/views/wishlist/delete_wishlistitem.js.erb
$('#<%= dom_id(@wishlistitem) %>').fadeOut();

app/views/wishlist/show.html.erb
<%= div_for(@wishlistitems) do |wishlistitem| %>
        <div class="wishlistitem-container">
                <a href="<%= wishlistitem.url %>">
                        <div class="wishlistitem-header">
                                <h3><%= wishlistitem.title %></h3>
                        </div>
                </a>
                <div class="wishlistitem-image">
                        <img src="<%= wishlistitem.image %>"/>
                </div>
                <div class="wishlistitem-footer">
                        <p>Price: $<%= wishlistitem.price %></p>
                        <p>Saved At: <%= wishlistitem.created_at.in_time_zone('Eastern Time (US & Canada)') %> </p>
                        <%= button_to 'Delete', delete_wishlistitem_path(wishlistitem.id), method: :delete, remote: true %>
                </div>
        </div>
<% end %>